MAX_HEADING_LENGTH: 7
MAX_HEADING_CONTENT_LENGTH: 200
MAX_HEADING_UNDERLINE_LENGTH: 200
MAX_HTML_HEADING_ATTRIBUTES_LENGTH: 100
MAX_LIST_ITEM_LENGTH: 200
MAX_NESTED_LIST_ITEMS: 6
MAX_LIST_INDENT_SPACES: 7
MAX_BLOCKQUOTE_LINE_LENGTH: 200
MAX_BLOCKQUOTE_LINES: 15
MAX_CODE_BLOCK_LENGTH: 1500
MAX_CODE_LANGUAGE_LENGTH: 20
MAX_INDENTED_CODE_LINES: 20
MAX_TABLE_CELL_LENGTH: 200
MAX_TABLE_ROWS: 20
MAX_HTML_TABLE_LENGTH: 2000
MIN_HORIZONTAL_RULE_LENGTH: 3
MAX_SENTENCE_LENGTH: 400
MAX_QUOTED_TEXT_LENGTH: 300
MAX_PARENTHETICAL_CONTENT_LENGTH: 200
MAX_NESTED_PARENTHESES: 5
MAX_MATH_INLINE_LENGTH: 100
MAX_MATH_BLOCK_LENGTH: 500
MAX_PARAGRAPH_LENGTH: 1000
MAX_STANDALONE_LINE_LENGTH: 800
MAX_HTML_TAG_ATTRIBUTES_LENGTH: 100
MAX_HTML_TAG_CONTENT_LENGTH: 1000
LOOKAHEAD_RANGE: 100